// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvzOqZbDNajTgJ_xdPLPEmG9nhDGG6jQ',
    appId: '1:816470915723:web:63b1c598859c0846ebf28e',
    messagingSenderId: '816470915723',
    projectId: 'senaequipos',
    authDomain: 'senaequipos.firebaseapp.com',
    storageBucket: 'senaequipos.firebasestorage.app',
    measurementId: 'G-Y25LT0005E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_MJTpaZVoJr85Gi6d6GOk4brkHQhxixU',
    appId: '1:816470915723:android:4b82e3ecae22f05bebf28e',
    messagingSenderId: '816470915723',
    projectId: 'senaequipos',
    storageBucket: 'senaequipos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyL8uJn7yCugtW-FthWTZwrOXbDStpPw',
    appId: '1:816470915723:ios:d06fceb683da94f9ebf28e',
    messagingSenderId: '816470915723',
    projectId: 'senaequipos',
    storageBucket: 'senaequipos.firebasestorage.app',
    iosBundleId: 'com.example.senaequipos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhyL8uJn7yCugtW-FthWTZwrOXbDStpPw',
    appId: '1:816470915723:ios:d06fceb683da94f9ebf28e',
    messagingSenderId: '816470915723',
    projectId: 'senaequipos',
    storageBucket: 'senaequipos.firebasestorage.app',
    iosBundleId: 'com.example.senaequipos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsvzOqZbDNajTgJ_xdPLPEmG9nhDGG6jQ',
    appId: '1:816470915723:web:58df8ad2e7f91e48ebf28e',
    messagingSenderId: '816470915723',
    projectId: 'senaequipos',
    authDomain: 'senaequipos.firebaseapp.com',
    storageBucket: 'senaequipos.firebasestorage.app',
    measurementId: 'G-JZE3RRBJ0Y',
  );
}
