// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYv_kP9ZwvlM4UZL8X4CBqzkVcU9_K6oM',
    appId: '1:331099110502:web:aede675decdff968a801a7',
    messagingSenderId: '331099110502',
    projectId: 'flutterfirebasebase',
    authDomain: 'flutterfirebasebase.firebaseapp.com',
    storageBucket: 'flutterfirebasebase.firebasestorage.app',
    measurementId: 'G-XT3GDNN9EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7QzC101olgitq_wvGmzaUdIqjdfDKtv4',
    appId: '1:331099110502:android:b60d4707c4b63771a801a7',
    messagingSenderId: '331099110502',
    projectId: 'flutterfirebasebase',
    storageBucket: 'flutterfirebasebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc6Fpy0Wm-AS2AwM8oDEzYdHOlaKY3aw',
    appId: '1:331099110502:ios:e3d2bd150ef2831ba801a7',
    messagingSenderId: '331099110502',
    projectId: 'flutterfirebasebase',
    storageBucket: 'flutterfirebasebase.firebasestorage.app',
    iosClientId: '331099110502-htpkikohenf580saa6u34opl5bt7efs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc6Fpy0Wm-AS2AwM8oDEzYdHOlaKY3aw',
    appId: '1:331099110502:ios:e3d2bd150ef2831ba801a7',
    messagingSenderId: '331099110502',
    projectId: 'flutterfirebasebase',
    storageBucket: 'flutterfirebasebase.firebasestorage.app',
    iosClientId: '331099110502-htpkikohenf580saa6u34opl5bt7efs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYv_kP9ZwvlM4UZL8X4CBqzkVcU9_K6oM',
    appId: '1:331099110502:web:56e68d5bb7d55e2aa801a7',
    messagingSenderId: '331099110502',
    projectId: 'flutterfirebasebase',
    authDomain: 'flutterfirebasebase.firebaseapp.com',
    storageBucket: 'flutterfirebasebase.firebasestorage.app',
    measurementId: 'G-BCJC4FEL97',
  );
}
