// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLMo1Bxj2VdYOtthIPYyl2pEt-VNWAc4',
    appId: '1:1026918662171:web:b0f51c507e4c6a3374b8be',
    messagingSenderId: '1026918662171',
    projectId: 'controltrack-ef3ff',
    authDomain: 'controltrack-ef3ff.firebaseapp.com',
    storageBucket: 'controltrack-ef3ff.firebasestorage.app',
    measurementId: 'G-Y3JWS1LMQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UB3xKAreE3DGmUeD_Rodo14BfeIF__Y',
    appId: '1:1026918662171:android:4ec76f513827102e74b8be',
    messagingSenderId: '1026918662171',
    projectId: 'controltrack-ef3ff',
    storageBucket: 'controltrack-ef3ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZqXWHICL1h8LkWto5EWtJkehRRKmNy3k',
    appId: '1:1026918662171:ios:192980b2502024ac74b8be',
    messagingSenderId: '1026918662171',
    projectId: 'controltrack-ef3ff',
    storageBucket: 'controltrack-ef3ff.firebasestorage.app',
    iosBundleId: 'com.example.controlTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZqXWHICL1h8LkWto5EWtJkehRRKmNy3k',
    appId: '1:1026918662171:ios:192980b2502024ac74b8be',
    messagingSenderId: '1026918662171',
    projectId: 'controltrack-ef3ff',
    storageBucket: 'controltrack-ef3ff.firebasestorage.app',
    iosBundleId: 'com.example.controlTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvLMo1Bxj2VdYOtthIPYyl2pEt-VNWAc4',
    appId: '1:1026918662171:web:0d7cdd602c93c17474b8be',
    messagingSenderId: '1026918662171',
    projectId: 'controltrack-ef3ff',
    authDomain: 'controltrack-ef3ff.firebaseapp.com',
    storageBucket: 'controltrack-ef3ff.firebasestorage.app',
    measurementId: 'G-XHMPZK9VLR',
  );
}
